### PR TITLE
Move pymake into its own module

### PR DESCRIPTION
**Pull request by Delaunay**
I would like to use pymake for another project, so I turned it into a package that will be installable using pip.
I also added github action CI.

You can merge it if you like the change.

### CODE REVIEW

**Comment by linuxlizard** [comment]
Holy cheese, thank you!  Give me a couple days to look this over and learn how everything is laid out now.

**Comment by Delaunay** [comment]
in a nutshell everything is inside a new folder/module `pymake`

so all the imports had to be modified to be `from vline import` to `from pymake.vline import` or from `import vline` to `import pymake.vline as vline`

The rest is pretty much the same, IIRC i moved a few test_XYZ to the test folder for consistency.
I would have liked to maybe move the test makefiles to their own folder but I did not want to modify too much, it is your project after all.

I also modified `test_makefile` to run each test file separately to get a bit of a more detailed report when one of the test file fails.

There are a few tests that are failing https://github.com/Delaunay/pymake/actions/runs/3971994324/jobs/6809464819
but I do not think it is related to the change

**Comment by linuxlizard** [comment]
I will move all those test makefiles into the test directory next.  

Thank you for fixing test_makefile()!  I wasn't sure how to do that.  A fixture is perfect.  

The test failures are probably because of some older code I haven't fixed yet. 

This is perfect timing because I'm about to embark on some big changes to better handle Recipes.  I've been too optimistic, to say the least, in my handling of leading tabs (aka recipeprefix).

**Comment by linuxlizard** [comment]
Merged!  I'm going to spend today getting all the tests 100% again. And finally learning Tox.

**Pull request merged**
